management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus

  metrics:
    enable:
      all: true
    export:
      jmx:
        enabled: true
      prometheus:
        enabled: true

  endpoint:
    health:
      show-components: always
      show-details: always